# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
            exclude_types: [markdown]
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
            types_or: [yaml, markdown]
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.62.3
      hooks:
          - id: terraform_fmt
          - id: terraform_validate
