# https://prettier.io/docs/en/options.html
overrides:
    - files:
          - "*.yaml"
          - "*.yml"
      options:
          tabWidth: 4
          printWidth: 88
    - files:
          - "*.md"
      options:
          tabWidth: 4
